# Use the (faster) container-based infrastructure, see also
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
dist: trusty
services:
  - docker

language: go
go:
  - "1.10"
go_import_path: github.com/stapelberg/dnsmasq_exporter


script:
  # Check whether files are syntactically correct.
  - "gofmt -l $(find . -name '*.go' | tr '\\n' ' ') >/dev/null"
  # Check whether files were not gofmt'ed.
  - "gosrc=$(find . -name '*.go' | tr '\\n' ' '); [ $(gofmt -l $gosrc 2>&- | wc -l) -eq 0 ] || (echo 'gofmt was not run on these files:'; gofmt -l $gosrc 2>&-; false)"
  - go tool vet .
  - go test -c
  - docker build --pull --no-cache --rm -t=dns -f travis/Dockerfile .
  - docker run -v $PWD:/usr/src:ro dns /bin/sh -c './dnsmasq_exporter.test -test.v'
